import { Routes } from '@angular/router';
import { StartScreenComponent } from './screens/start-screen/start-screen.component';
import { RecipesScreenComponent } from './screens/recipes-screen/recipes-screen.component';
import { RecipeDetailComponent } from './screens/recipe-detail/recipe-detail.component';
import { ProfileComponent } from './screens/profile/profile.component';
import { LoginpageComponent } from './screens/loginpage/loginpage.component';
import { RegisterpageComponent } from './screens/registerpage/registerpage.component';
import { ImprintComponent } from './screens/imprint/imprint.component';
import { PrivacyPolicyComponent } from './screens/privacy-policy/privacy-policy.component';
import { AdminDashboardComponent } from './screens/admin-dashboard/admin-dashboard.component';
import { SettingsComponent } from './screens/profile/settings/settings.component';
import { UserProfilePublicComponent } from './screens/profile/user-profile-public/user-profile-public.component';
import { FavoriteScreenComponent } from './screens/favorite-screen/favorite-screen.component';
import { CommentsComponent } from './screens/profile/comments/comments.component';
import { PublicCommentsComponent } from './screens/profile/user-profile-public/public-comments/public-comments.component';
import { PublicFavoritesComponent } from './screens/profile/user-profile-public/public-favorites/public-favorites.component';

export const routes: Routes = [
  { path: '', component: StartScreenComponent },
  { path: 'profile/settings', component: SettingsComponent },
  { path: 'recipe', component: RecipesScreenComponent },
  { path: 'recipe/:id', component: RecipeDetailComponent },
  { path: 'profile', component: ProfileComponent },
  { path: 'login', component: LoginpageComponent },
  { path: 'register', component: RegisterpageComponent },
  { path: 'imprint', component: ImprintComponent },
  { path: 'privacypolicy', component: PrivacyPolicyComponent },
  { path: 'admin', component: AdminDashboardComponent },
  { path: 'user/:username', component: UserProfilePublicComponent },
  { path: 'profile/favorites', component: FavoriteScreenComponent },
  { path: 'favorites', component: FavoriteScreenComponent },
  { path: 'profile/comments', component: CommentsComponent },
  { path: 'comments/:username', component: PublicCommentsComponent },
  { path: 'admin-dashboard', component: AdminDashboardComponent },
  { path: 'favorites/:username', component: PublicFavoritesComponent }
];
