services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpw
      MARIADB_DATABASE: fullstack_db
      MARIADB_USER: fs_user
      MARIADB_PASSWORD: fs_pw
      TZ: Europe/Berlin
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d
      - ./mariadb-data:/var/lib/mysql
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'mongo_fs_user'
      MONGO_INITDB_ROOT_PASSWORD: 'mongo_fs_pw'
      MONGO_INITDB_DATABASE: 'mongo_fullstack_db'
      TZ: Europe/Berlin
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:
    driver: bridge
